### ISSUE TITLE
Charts is not show

### ISSUE THREAD

**Issue by fernandaalayon** [mkolisnyk/cucumber-reports#63]
Actually the charts of my overwiew report is not showing fine, then I attachement the screen to you see how is showing
![viewcharts](https://cloud.githubusercontent.com/assets/17204984/13017889/cb98a99a-d194-11e5-92f4-6065378d87ce.png)

**Comment by mkolisnyk** [comment]
This problem was supposed to be fixed with #36 issue and changes are available since 1.0.0 version. Please, update your library dependency to version 1.0.1 (which is the latest at the moment). It should work now. If not, let me know I'll play around test results.

**Comment by fernandaalayon** [comment]
I am using the version 1.0.1 and in the reports the charts i no displaying correctly only show a rectangle. I atachment the screen the report, 
![viewchartsii](https://cloud.githubusercontent.com/assets/17204984/13053088/8ba568bc-d3d0-11e5-9ce1-265ff659bc3e.png)

**Comment by mkolisnyk** [comment]
OK. I'll try to reproduce the report which is supposed to generate the same output as you show on the last picture. Not sure what causes issue, maybe I've made some changes to the latter version (which isn't released yet). But in order to have complete information I'd like to know some more details:

1) Which browser do you use? I see the first screenshot is definitely from Eclipse default browser. Did you try any other browser (like Chrome, Firefox)?

2) Which operating system you are running under? I've checked on Mac and charts are rendered OK, I can check Windows 8 as well but it's useful to know which environment you see the problem in.

If that wouldn't help I can make a release. How knows, maybe I've fixed this issue after 1.0.1

**Comment by fernandaalayon** [comment]
On chrome and firefox the problem is persist.

I work on Windows 8.1 pro OS

**Comment by mkolisnyk** [comment]
Still unable to reproduce the problem. But I have newer library version. I've published a new version of the library. Please, update your dependency to **1.0.2** version and let me know if it works for you or not.

**Comment by fernandaalayon** [comment]
I updated the version, but when I Try to run the test, the console display the error

> cucumber.runtime.CucumberException: java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:114)
	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:87)
	at cucumber.runtime.RuntimeOptions.getPlugins(RuntimeOptions.java:241)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:287)
	at com.sun.proxy.$Proxy15.uri(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.uri(JUnitReporter.java:160)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:68)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.runChild(ExtendedCucumber.java:75)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.runChild(ExtendedCucumber.java:25)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:101)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.newDocument(Unknown Source)
	at cucumber.runtime.formatter.JUnitFormatter.<init>(JUnitFormatter.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:107)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 40 more

**Comment by mkolisnyk** [comment]
This looks like a conflict of dependencies and can be fixed by slight changes in your pom.xml. The cucumber-reports dependency should look like:

```xml
<dependency>
    <groupId>com.github.mkolisnyk</groupId>
    <artifactId>cucumber-reports</artifactId>
    <version>1.0.2</version>
        <exclusions>
	        <exclusion>
		        <groupId>xml-apis</groupId>
	        </exclusion>
	        <exclusion>
		        <groupId>fop</groupId>
	        </exclusion>
        </exclusions>
</dependency>
<dependency>
    <groupId>xml-apis</groupId>
    <artifactId>xml-apis</artifactId>
    <version>1.4.01</version>
</dependency>
```

Note the second dependency. This way we explicitly define which **xml-apis** version we should choose.

This should help with your current issue. At the same time it is something to be fixed in the library. I've created dedicated issue #65 for that

**Comment by fernandaalayon** [comment]
Hi, I have a new problems. I changed my pom.xml as you indicate, but:
- The charts is not show correctly
- And now is displaying this error:

> org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
file:/C:/Users/Seven4n/Documents/workspace/litigando/AutomatedTestLitimovil/target/General/ExtendedReport/GeneralTest/temp1455811167252/0.svg:-1
The attribute "d" of the element <path> is invalid
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at com.github.mkolisnyk.cucumber.reporting.CucumberResultsCommon.convertSvgToPng(CucumberResultsCommon.java:366)
	at com.github.mkolisnyk.cucumber.reporting.CucumberResultsCommon.replaceSvgWithPng(CucumberResultsCommon.java:388)
	at com.github.mkolisnyk.cucumber.reporting.CucumberResultsCommon.exportToPDF(CucumberResultsCommon.java:402)
	at com.github.mkolisnyk.cucumber.reporting.CucumberResultsOverview.executeOverviewReport(CucumberResultsOverview.java:126)
	at com.github.mkolisnyk.cucumber.reporting.CucumberResultsOverview.executeFeaturesOverviewReport(CucumberResultsOverview.java:142)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runOverviewReport(ReportRunner.java:42)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:167)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:111)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
file:/C:/Users/Seven4n/Documents/workspace/litigando/AutomatedTestLitimovil/target/General/ExtendedReport/GeneralTest/temp1455811169564/0.svg:-1
The attribute "d" of the element <path> is invalid
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at com.github.mkolisnyk.cucumber.reporting.CucumberResultsCommon.convertSvgToPng(CucumberResultsCommon.java:366)
	at com.github.mkolisnyk.cucumber.reporting.CucumberResultsCommon.replaceSvgWithPng(CucumberResultsCommon.java:388)
	at com.github.mkolisnyk.cucumber.reporting.CucumberResultsCommon.exportToPDF(CucumberResultsCommon.java:402)
	at com.github.mkolisnyk.cucumber.reporting.CucumberResultsOverview.executeOverviewReport(CucumberResultsOverview.java:126)
	at com.github.mkolisnyk.cucumber.reporting.CucumberCoverageOverview.executeCoverageReport(CucumberCoverageOverview.java:168)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runCoverageReport(ReportRunner.java:112)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:171)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:111)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by mkolisnyk** [comment]
Let's start with the second problem. This happens during HTML to PDF conversion for overview report. Since exception happens at the latest stage of report processing it shouldn't affect your run. On the library side this is handled by try-catch black, so the stack trace you see is just console output. 

So, it shouldn't be a blocker for you right now. Just go to the output folder and make sure that HTML reports are generated (which is definitely the case for you).

But it's definitely an annoying problem which is needed to be fixed. I've already created issue #64 which appears exactly in that area, so an input from you would be helpful. Could you send me the feature overview HTML file to my e-mail? It is kolesnik.nickolay@gmail.com . I'll use it to debug the functionality.

Even more, such error appears when the arc object in chart is not defined properly, especially when it comes to the parameter which indicates whether we should draw greater or smaller arc. And this potentially causes your first problem. So, I'd like to know how those charts are generated on your machine. Maybe if I find the root cause, I'll fix your both problems.

**Comment by mkolisnyk** [comment]
The problem is with string formatting for floating point numbers on different locales (in some locales comma is used instead of dot for decimal numbers). Taking into development

**Comment by mkolisnyk** [comment]
Work on the issue is done. Fix will be available on version **1.0.3**. Currently as the temporary workaround it is possible to put the following instruction at some pre-condition code (either hook or before-method):

```java
Locale.setDefault(Locale.US);
```

That should help at the moment before fix is published. The work on issue is done for now.

**Comment by fernandaalayon** [comment]
Thank you, now the report's charts is show correctly, So now I hope
delivery version 1.0.3 to update tge dependency.

Thank you so much


On Fri, Feb 19, 2016 at 11:29 AM, Myk Kolisnyk <notifications@github.com>
wrote:

> Work on the issue is done. Fix will be available on version *1.0.3*.
> Currently as the temporary workaround it is possible to put the following
> instruction at some pre-condition code (either hook or before-method):
>
> Locale.setDefault(Locale.US);
>
> That should help at the moment before fix is published. The work on issue
> is done for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mkolisnyk/cucumber-reports/issues/63#issuecomment-186288078>
> .
>



-- 

*Irma Fernanda Alayón Perilla*
*Tecnóloga** en Informática*
*Est. Ingeniería de Sistemas*
*UNIMINUTO*
